name: Deploy CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: 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
          VERCEL_TOKEN: o6xsHB5Czit7vUdggPHJi19b
          VERCEL_ORG_ID: lzx8lQi6ENGR0QPdONNUpSgK
          VERCEL_PROJECT_ID: prj_UB0lE8olH7lNCIndld72qasV5Pn4
