name: deploy website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: o6xsHB5Czit7vUdggPHJi19b # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: '--prod' #Optional
          vercel-org-id: lzx8lQi6ENGR0QPdONNUpSgK #Required
          vercel-project-id: prj_UB0lE8olH7lNCIndld72qasV5Pn4 #Required
          working-directory: ./sub-directory
